# Generated by Django 3.2.4 on 2023-09-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('tipo_genero', models.TextField(db_column='tipo_genero')),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
    ]
